language: java

jdk:
  - openjdk8

before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - openssl aes-256-cbc -K $encrypted_d136eb043a05_key -iv $encrypted_d136eb043a05_iv -in signingkey.asc.enc -out signingkey.asc -d
  - gpg2 --keyring=$TRAVIS_BUILD_DIR/pubring.gpg --no-default-keyring --import signingkey.asc
  - gpg2 --allow-secret-key-import --keyring=$TRAVIS_BUILD_DIR/secring.gpg --no-default-keyring --import signingkey.asc

after_success:
  - mvn clean test jacoco:report-aggregate coveralls:report -Pcode-coverage
  - mvn clean deploy -Prelease
