language: java

jdk:
  - openjdk8

before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

after_success:
  - mvn clean test jacoco:report-aggregate coveralls:report -Pcode-coverage
  - mvn clean deploy -Prelease
