language: java
jdk:
  - openjdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_9d42c6f30771_key -iv $encrypted_9d42c6f30771_iv -in .signingkey.asc.enc -out signingkey.asc -d
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - sh -c "$GPG_EXECUTABLE --batch --import signingkey.asc"
  - sh -c "$GPG_EXECUTABLE --list-keys"
after_success:
  - mvn clean test jacoco:report-aggregate coveralls:report -Pcode-coverage
  - mvn clean deploy -Prelease
