language: java

jdk:
  - openjdk8

before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
  - openssl aes-256-cbc -K $encrypted_9d42c6f30771_key -iv $encrypted_9d42c6f30771_iv -in .signingkey.asc.enc -out signingkey.asc -d
  - sh -c "$GPG_EXECUTABLE --batch --import signingkey.asc"

script:
  - mvn test -B || travis_terminate 1
  - mvn clean test jacoco:report-aggregate coveralls:report -B -Pcode-coverage || travis_terminate 1
  - mvn clean deploy -DskipTests -Prelease || travis_terminate 1
